Response.destroy_all
Question.destroy_all

question1 = Question.create(label: 'Vous êtes :', order: 1)
question2 = Question.create(label: 'Vous êtes à la recherche de :', order: 2)
question3 = Question.create(label: 'Vos amis dites de vous que vous êtes :', order: 3)
question4 = Question.create(label: "Vous êtes à la recherche d'une personne :", order: 4)
question5 = Question.create(label: 'Quels types de films préférez-vous ?', order: 5)
question6 = Question.create(label: 'Quels types de musiques préférez-vous ?', order: 6)
question7 = Question.create(label: 'Quels sont vos sports préférés ?', order: 7)
question8 = Question.create(label: 'Quels types de cuisine préférez-vous ?', order: 8)
question9 = Question.create(label: 'Quels types de littérature préférez-vous ?', order: 9)
question10 = Question.create(label: 'A quelle fréquence lisez-vous ? (toutes catégories confondues)', order: 10)
question11 = Question.create(label: "Êtes-vous intéressé par l'horoscope ?", order: 11)
question12 = Question.create(label: 'Quels sont vos hobbies ?', order: 12)
question13 = Question.create(label: 'Quels animaux préférez-vous ?', order: 13)

response1 = Response.create(label: "Femme", question: question1)
response2 = Response.create(label: "Homme", question: question1)
response3 = Response.create(label: "Non-binaire", question: question1)

response4 = Response.create(label: "Femme", question: question2)
response5 = Response.create(label: "Homme", question: question2)
response6 = Response.create(label: "Non-binaire", question: question2)

response7 = Response.create(label: "Extraverti", question: question3)
response8 = Response.create(label: "Introverti", question: question3)
response9 = Response.create(label: "Ambitieux", question: question3)
response10 = Response.create(label: "Sociable", question: question3)
response11 = Response.create(label: "Calme", question: question3)
response12 = Response.create(label: "Drôle", question: question3)
response13 = Response.create(label: "Timide", question: question3)
response14 = Response.create(label: "Réservé", question: question3)
response15 = Response.create(label: "Mélancolique", question: question3)
response16 = Response.create(label: "Hyperactif", question: question3)
response17 = Response.create(label: "Créatif", question: question3)
response18 = Response.create(label: "Sensible", question: question3)
response19 = Response.create(label: "Romantique", question: question3)
response20 = Response.create(label: "Cultivé", question: question3)

response21 = Response.create(label: "Extraverti", question: question4)
response22 = Response.create(label: "Introverti", question: question4)
response23 = Response.create(label: "Ambitieux", question: question4)
response24 = Response.create(label: "Sociable", question: question4)
response25 = Response.create(label: "Calme", question: question4)
response26 = Response.create(label: "Drôle", question: question4)
response27 = Response.create(label: "Timide", question: question4)
response28 = Response.create(label: "Réservé", question: question4)
response29 = Response.create(label: "Mélancolique", question: question4)
response30 = Response.create(label: "Hyperactif", question: question4)
response31 = Response.create(label: "Créatif", question: question4)
response32 = Response.create(label: "Sensible", question: question4)
response33 = Response.create(label: "Romantique", question: question4)
response34 = Response.create(label: "Cultivé", question: question4)

response35 = Response.create(label: "Action", question: question5)
response36 = Response.create(label: "Comédie", question: question5)
response37 = Response.create(label: "Drame", question: question5)
response38 = Response.create(label: "Science-fiction", question: question5)
response39 = Response.create(label: "Thriller", question: question5)
response40 = Response.create(label: "Horreur", question: question5)
response41 = Response.create(label: "Animé", question: question5)
response42 = Response.create(label: "Historique", question: question5)
response43 = Response.create(label: "Biographie", question: question5)
response44 = Response.create(label: "Documentaire", question: question5)

response45 = Response.create(label: "Rock", question: question6)
response46 = Response.create(label: "Pop", question: question6)
response47 = Response.create(label: "Rap", question: question6)
response48 = Response.create(label: "Jazz", question: question6)
response49 = Response.create(label: "Classique", question: question6)
response50 = Response.create(label: "Métal", question: question6)
response51 = Response.create(label: "Hip-Hop", question: question6)
response52 = Response.create(label: "RnB", question: question6)
response53 = Response.create(label: "Blues", question: question6)
response54 = Response.create(label: "Electro", question: question6)
response55 = Response.create(label: "Reggae", question: question6)

response56 = Response.create(label: "Football", question: question7)
response57 = Response.create(label: "Basketball", question: question7)
response58 = Response.create(label: "Rugby", question: question7)
response59 = Response.create(label: "Athlétisme", question: question7)
response60 = Response.create(label: "Volleyball", question: question7)
response61 = Response.create(label: "Tennis", question: question7)
response62 = Response.create(label: "Tennis de table", question: question7)
response63 = Response.create(label: "Natation", question: question7)
response64 = Response.create(label: "Gymnastique", question: question7)
response65 = Response.create(label: "Danse", question: question7)
response66 = Response.create(label: "Fitness", question: question7)
response67 = Response.create(label: "Escalade", question: question7)
response68 = Response.create(label: "Sports de combat", question: question7)
response69 = Response.create(label: "Equitation", question: question7)
response70 = Response.create(label: "Skate", question: question7)
response71 = Response.create(label: "Sports automobiles", question: question7)
response72 = Response.create(label: "Aucun", question: question7)

response73 = Response.create(label: "Asiatique", question: question8)
response74 = Response.create(label: "Français", question: question8)
response75 = Response.create(label: "Italien", question: question8)
response76 = Response.create(label: "Oriental", question: question8)
response77 = Response.create(label: "Indien", question: question8)
response78 = Response.create(label: "Fast-food", question: question8)
response79 = Response.create(label: "Africain", question: question8)
response80 = Response.create(label: "Russe", question: question8)
response81 = Response.create(label: "Mexicain", question: question8)

response82 = Response.create(label: "Manga", question: question9)
response83 = Response.create(label: "Bande dessinée", question: question9)
response84 = Response.create(label: "Roman d'amour", question: question9)
response85 = Response.create(label: "Roman policier", question: question9)
response86 = Response.create(label: "Roman épistolaire", question: question9)
response87 = Response.create(label: "Roman classique", question: question9)
response88 = Response.create(label: "Fantaisie", question: question9)
response89 = Response.create(label: "Science-fiction", question: question9)
response90 = Response.create(label: "Théâtre", question: question9)
response91 = Response.create(label: "Horreur", question: question9)
response92 = Response.create(label: "Nouvelle fiction", question: question9)

response93 = Response.create(label: "Tous les jours", question: question10)
response94 = Response.create(label: "2 à 3 fois par semaine", question: question10)
response95 = Response.create(label: "Quelques fois par mois", question: question10)
response96 = Response.create(label: "Quelques fois par an", question: question10)
response97 = Response.create(label: "Jamais", question: question10)

response98 = Response.create(label: "Oui", question: question11)
response99 = Response.create(label: "Un peu", question: question11)
response100 = Response.create(label: "Non", question: question11)

response100 = Response.create(label: "Musée", question: question12)
response101 = Response.create(label: "Théâtre", question: question12)
response102 = Response.create(label: "Opéra", question: question12)
response103 = Response.create(label: "Peinture", question: question12)
response104 = Response.create(label: "Voyage", question: question12)
response105 = Response.create(label: "Sortie nocturne", question: question12)
response106 = Response.create(label: "Cinéma", question: question12)
response107 = Response.create(label: "Jeux vidéo", question: question12)
response108 = Response.create(label: "Littérature", question: question12)
response109 = Response.create(label: "Sport", question: question12)
response110 = Response.create(label: "Série", question: question12)
response111 = Response.create(label: "Balade", question: question12)
response112 = Response.create(label: "Télévision", question: question12)

response113 = Response.create(label: "Chats", question: question13)
response114 = Response.create(label: "Chiens", question: question13)
response115 = Response.create(label: "Chevaux", question: question13)
response116 = Response.create(label: "Oiseaux", question: question13)
response117 = Response.create(label: "Poissons", question: question13)
response118 = Response.create(label: "Reptiles", question: question13)
response119 = Response.create(label: "Rongeurs", question: question13)
